variables:
  S3_BUCKET_NAME: "ab-in-den-urlaub-fallback"

deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "README.md" --exclude ".gitlab-ci.yml"
  only:
  - tags

pages:
  image: alpine:latest
  script:
  - mkdir -p ./public
  - cp ./index.html ./assets/* ./public/
  artifacts:
    paths:
    - public
  except:
  - tags