variables:
  S3_BUCKET_NAME: "ab-in-den-urlaub-fallback"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "README.md" --exclude ".gitlab-ci.yml"
  only:
  - tags

pages:
  image: alpine:latest
  script:
  - mkdir -p ./public
  - cp -R ./index.html ./assets/ ./public/
  artifacts:
    paths:
    - public
  except:
  - tags